### ISSUE TITLE
$data->attrs 属性设置为三个元素，页面上还是只会显示两种规格

### ISSUE THREAD

**Issue by LISONGDASHUAIGE** [lty5240/dcat-easy-sku#1]
![image](https://user-images.githubusercontent.com/24515158/103396155-7f58a880-4b6c-11eb-8d32-f751af6e5b22.png)
![image](https://user-images.githubusercontent.com/24515158/103396162-88497a00-4b6c-11eb-9f44-c0e88cca1cfe.png)

**Comment by light-speak** [comment]
已在1.0.1版本修复
