### ISSUE TITLE
Uncaught SyntaxError: Unexpected token d in JSON at position 0     at JSON.parse (<anonymous>)     at SKU.getSkuAttr 

### ISSUE THREAD

**Issue by 377123** [lty5240/dcat-easy-sku#3]
https://github.com/lty5240/dcat-easy-sku/blob/89cbd4bb25f13087554ae7456fabece89e3d13f0/resources/assets/js/dcat-easy-sku.js#L170

**Comment by light-speak** [comment]
好的，等我看看
