### ISSUE TITLE
sku的图片显示问题

### ISSUE THREAD

**Issue by LISONGDASHUAIGE** [lty5240/dcat-easy-sku#5]
![3 @9JL2EH{H92 TDS7_O334](https://user-images.githubusercontent.com/24515158/116362281-78992400-a834-11eb-8aca-dc3c184a6dec.png)
![P 8FV(T_GDMX_YKW%OET1RX](https://user-images.githubusercontent.com/24515158/116362288-79ca5100-a834-11eb-92e9-2ac6b2e57f14.png)
![R7}3IOBHST$Y@ 1B8428V0U](https://user-images.githubusercontent.com/24515158/116362300-7cc54180-a834-11eb-9055-523437b339c5.png)
数据打印出来，这个3.0 a450的图片应该是1f.png，但是页面上显示的是016.png

**Comment by light-speak** [comment]
无法重现
