### ISSUE TITLE
支持多属性分组吗？

### ISSUE THREAD

**Issue by shunhua** [lty5240/dcat-easy-sku#6]
例如这种：
![image](https://user-images.githubusercontent.com/11988030/118444793-2f940b80-b720-11eb-99f7-3123fc76a708.png)

**Comment by light-speak** [comment]
没理解

**Comment by shunhua** [comment]
就是软件类属性  和 硬件类属性 属于分组 下面的属于分组项
软件类属性
                &nbsp；测试气体：天然气

**Comment by light-speak** [comment]
对这方面没太多了解，有没有地方可以体验的，我试试

**Comment by shunhua** [comment]
没啥体验的  就是sku 里面的规格分组啊 像淘宝、京东一样
